### PR TITLE
Sophia Cheng Pull Request 190J

### PR DESCRIPTION
**Pull request by sophiacheng01**
- Added image to assets and bio to _staffers

### CODE REVIEW

**Comment by ykharitonova** [comment]
@sophiacheng01 What kind of art did you teach? Was it drawing or painting?

I'm learning to use Procreate on my iPad, and that's been a fun journey.

**Comment by sophiacheng01** [comment]
I taught art to middle schoolers so it was mostly basic drawing skills but we tried to integrate some watercolor painting as well. I used to paint a lot of acrylic but after getting an iPad this year I've been exploring Procreate too. Although I'm not sure I'm using it to its best ability so if you have any tips let me know !

**Comment by ykharitonova** [comment]
@sophiacheng01 I love watercolors, although, they can be so maddening, when they don't do what you have in mind. :-)

For getting more comfortable with Procreate (and a "watercolor" flavor), I really like Teela's tutorials: https://www.youtube.com/user/everytues. 
I also enjoy the style and the artwork of Gal Shir: https://www.youtube.com/channel/UCA1ZyvPnZ1D-3xlpCM6-CrQ.

Let me know if you have any favorite resources/projects.

**Comment by sophiacheng01** [comment]
I'll definitely check those out ! I don't really have any procreate specific projects that I can think of off the top of my head, but I'll let you know if any come up :) I know a lot of artists use the Jingsketch brush pack, I haven't gotten it yet but I am strongly considering it.

**Comment by ykharitonova** [comment]
I look forward to seeing which ones you end up trying out.

**Pull request merged**
